general:
  device: 'mps'
  data_dir: '../Data/SMAP_MSL/'
  model_dir: 'checkpoints'

data:
  SMAP:
    win_size: 100
    batch_size: 512
    anomaly_ratio: 0.5

model:
  gamma: 2.0
  sigma: 1.0
  lambda_smooth: 0.01
  SMAP:
    enc_in: 25
    c_out: 25
    e_layers: 3

training:
  n_epochs: 3
  lr: 1.0e-5
  k: 3

testing:
  temperature: 50


