data:
  MSL:
    anomaly_ratio: 0.5
    batch_size: 256
    win_size: 100
  SMAP:
    anomaly_ratio: 0.5
    batch_size: 512
    win_size: 100
general:
  data_dir: ../Data/SMAP_MSL/
  device: mps
  model_dir: checkpoints
model:
  MSL:
    c_out: 55
    e_layers: 3
    enc_in: 55
  SMAP:
    c_out: 25
    e_layers: 3
    enc_in: 25
  gamma: 1.0
  lambda_smooth: 0.001
  sigma: 0.5
testing:
  temperature: 10
training:
  k: 5
  lr: 1.0e-05
  n_epochs: 3
